name: Deploy Lambda Function

on:
  workflow_call:
    secrets:
      ACCESS_KEY:
        required: true
      SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Lambda container image
        run: |
          docker pull ghcr.io/bblue530/backup_repo_lambda:latest

      - name: Get and mask account ID
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "::add-mask::$ACCOUNT_ID"
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      - name: Push image to AWS ECR
        run: |
          aws ecr describe-repositories --repository-names repo_backup_to_s3 || \
            aws ecr create-repository --repository-name repo_backup_to_s3

          aws ecr get-login-password --region eu-north-1 | \
            docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com

          docker tag ghcr.io/bblue530/backup_repo_lambda:latest \
            $ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/repo_backup_to_s3:latest

          docker push $ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/repo_backup_to_s3:latest

      - name: Update Lambda to use container image
        run: |
          aws lambda update-function-code \
            --function-name repo_backup_to_s3 \
            --image-uri $ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/repo_backup_to_s3:latest
